---

- name: synchronize systemd time
  changed_when: false
  systemd:
    state: restarted
    name: systemd-timesyncd.service

- name: Sleep for 5 seconds and continue with play
  wait_for:
    timeout: 5

- name: install python3 and python3-apt
  changed_when: false
  shell:
    cmd: apt-get install -y python3 python3-apt
    warn: no
