---

- name: install prometheus-blackbox-exporter
  apt:
    state: present
    name: prometheus-blackbox-exporter

- name: copy systemd override
  notify: restart blackbox-exporter
  copy:
    src: override.conf
    dest: /etc/systemd/system/prometheus-blackbox-exporter.service.d/

- name: copy blackbox-exporter config
  notify: restart blackbox-exporter
  copy:
    src: blackbox.yml
    dest: /etc/prometheus/
