image: debian:bullseye

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
- test

ansible_lint:
  stage: test
  before_script:
  - apt update
  - apt install -qq -y ansible-lint
  script:
  - ansible-lint playbook.yml
