---
- hosts: gateways
  become: true
  roles:
    # - role: prepare_ansible
    #   tags: [prepare_ansible]
    - role: ffhl_access
      tags: [ffhl_access]
    - role: base
      tags: [base]
    - role: gwvpn
      tags: [gwvpn]
    - role: base_bird
      tags: [base_bird, bird]
    - role: peering
      tags: [peering]
    - role: meshvpn
      tags: [meshvpn]
    - role: dns_common
      tage: [dns_common, dns]

# - hosts: kaisertor
#   become: true
#   roles:
#     - icvpn
