---
- hosts: gateways
  become: true
  max_fail_percentage: 0
  roles:
    # - role: prepare_ansible
    #   tags: [prepare_ansible]
    - role: ffhl_access
      tags: [ffhl_access]
    - role: common_gateway
      tags: [common_gateway, common]
    - role: underlay_vpn
      tags: [underlay_vpn, gateways]
    - role: gwvpn
      tags: [gwvpn]
    - role: bird_common
      tags: [bird_common, bird]
    - role: peering
      tags: [peering]
    - role: meshvpn
      tags: [meshvpn]
    - role: dns_common
      tage: [dns_common, dns]

# - hosts: kaisertor
#   become: true
#   roles:
#     - icvpn
