gateways:
  hosts:
    kaisertor:
      ansible_ssh_host: kaisertor.mesh.ffhl.chaotikum.org
    huextertor:
      ansible_ssh_host: huextertor.mesh.ffhl.chaotikum.org
    # muehlentor:
  vars:
    ansible_python_interpreter: /usr/bin/env python2
    ansible_ssh_user: root
