gateways:
  hosts:
    kaisertor:
      ansible_ssh_host: kaisertor.mesh.ffhl.chaotikum.org
    huextertor:
      ansible_ssh_host: huextertor.mesh.ffhl.chaotikum.org
    holstentor:
      ansible_ssh_host: holstentor.mesh.ffhl.chaotikum.org
    muehlentor:
      ansible_ssh_host: muehlentor.mesh.ffhl.chaotikum.org
    test:
      ansible_ssh_host: test.mesh.ffhl.chaotikum.org
  vars:
    ansible_python_interpreter: /usr/bin/env python3
    ansible_ssh_user: root
