gateways:
  vars:
    ansible_python_interpreter: /usr/bin/env python3
    ansible_ssh_user: root
  hosts:
    kaisertor:
      ansible_ssh_host: kaisertor.mesh.ffhl.chaotikum.org
    huextertor:
      ansible_ssh_host: huextertor.mesh.ffhl.chaotikum.org
    holstentor:
      ansible_ssh_host: holstentor.mesh.ffhl.chaotikum.org
    muehlentor:
      ansible_ssh_host: muehlentor.mesh.ffhl.chaotikum.org
    gw05:
      ansible_ssh_host: gw05.ffhl.chaotikum.org
service_hosts:
  vars:
    ansible_python_interpreter: /usr/bin/env python3
    ansible_ssh_user: root
  hosts:
    srv02:
      ansible_ssh_host: srv02.luebeck.freifunk.net
