---
- hosts: gateways
  become: yes
  roles:
    - base
    - role: meshvpn
      tags: [meshvpn]
    - role: ffhl_nameserver
      tags: [nameserver]


- hosts: kaisertor
  become: yes
  roles:
    - icvpn

- hosts: service_hosts
  become: yes
  roles:
    - services
    - ffhl_nameserver
