---
- lineinfile:
    path: /etc/apt/sources.list
    # regexp: '^deb .* main$'
    line: deb http://deb.debian.org/debian bullseye main


- name: apt python update
  command: apt-get update

- name: install python-apt
  command: apt-get install -y python-apt

- name: install tools
  apt:
    update_cache: yes
    state: present
    name:
      - apt-file
      - batctl
      - bind9
      - bird2
      - bridge-utils
      - curl
      - dnsutils
      - fastd
      - git
      - haveged
      - htop
      - iftop
      - iperf3
      - iptables-persistent
      - iputils-ping
      - isc-dhcp-server
      - ntp
      - openssh-client
      - openssh-server
      - prometheus-bind-exporter
      # - prometheus-bird-exporter
      - prometheus-node-exporter
      - python-apt
      - python3-yaml
      - radvd
      - tcpdump
      - tinc
      - vim
      - wget
      - socat
      - jq

- name: load batman-adv
  modprobe:
    name: batman-adv
    state: present
