#!/bin/bash
set -e

ip link set address {{ fastd_gw_mac }} dev $INTERFACE
ip link set up $INTERFACE
# for some reason it seems that adding the interface too fast
# to bat0 will cause batman_adv to remove them because they are 'deactivated'
sleep 5
echo "Adding interface $INTERFACE to bat0"
ip link add bat0 type batadv || true
batctl if add $INTERFACE
batctl gw_mode server 50000/25000
batctl network_coding disable
