---

- name: install packages
  tags: [dns, powerdns]
  apt:
    state: present
    name:
      - dnsdist

- name: copy dnsdist config
  copy:
    src: dnsdist/dnsdist.conf
    dest: /etc/dnsdist/
  notify: restart dnsdist
