---

- name: add apt preferences
  copy:
    src: apt/preferences.d
    dest: /etc/apt/

- name: add sources.list
  copy:
    src: apt/debian_bookworm.list
    dest: /etc/apt/sources.list



- name: remove packages that are not needed
  apt:
    update_cache: yes
    state: absent
    name:
      - cron-apt
      - mutt
      - rsyslog

- name: install tools
  apt:
    autoremove: yes
    update_cache: yes
    state: latest
    name:
      # necessary packets
      - systemd
      - batctl
      - fastd
      - git
      - haveged
      - iproute2
      - iptables-persistent
      - openssh-server
      - prometheus-node-exporter
      # - systemd-timesyncd causes dependency hell atm
      # tools
      - apt-file
      - bridge-utils
      - curl
      - dnsutils
      - htop
      - iftop
      - iperf3
      - iputils-ping
      - jq
      - molly-guard
      - openssh-client
      - python3-yaml
      - socat
      - tcpdump
      - vim
      - wget
      - rsync
      - nmap

- name: load batman-adv
  modprobe:
    name: batman-adv
    state: present
