---

# - name: restart services
#   systemd:
#     enabled: no
#     name: "{{ item }}"
#   with_items:
#     - batman.service

- name: stop, mask and disable selected services
  tags: [systemd]
  systemd:
    masked: yes
    state: stopped
    enabled: no
    name: "{{ item }}"
  loop: "{{ masked_services | default('[]') }}"
