---

- name: disable old gwvpn
  systemd:
    name: fastd@ffhl_mesh_gwvpn.service
    enabled: false
    state: stopped

- name: remove old files
  file:
    state: absent
    path: "{{ item }}"
  loop:
    - /etc/fastd/ffhl_mesh_gwvpn
    - /etc/fastd/ffhl_mesh_gwvpn
    - /etc/fastd/ffhl_mesh_gwvpn/fastd.conf
    - /etc/fastd/ffhl_mesh_gwvpn/fastd-up


- name: network config
  notify: reload networkd
  template:
    src: 10-tunnel.network.j2
    dest: "/etc/systemd/network/10-gre_bb_{{ '%02d' | format(hostvars[item].gwid) }}.network"
  loop: "{{ groups['gateways'] | difference(inventory_hostname) }}"
