---

- name: check nginx config
  command:
    cmd: nginx -t

- name: restart nginx
  systemd:
    state: restarted
    name: nginx.service

- name: restart caddy
  systemd:
    state: restarted
    name: caddy.service
