# Sample config for Prometheus.

global:
  scrape_interval: 60s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 120s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ["localhost:9093"]

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "first_rules.yml"
  #- "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "hopglass"
    static_configs:
      - targets: ["srv02.ffhl.de:4000"]
  - job_name: "hosts"
    static_configs:
      - targets:
        - "muehlentor.mesh.ffhl.chaotikum.org:9100"
        - "holstentor.mesh.ffhl.chaotikum.org:9100"
        - "kaisertor.mesh.ffhl.chaotikum.org:9100"
        - "huextertor.mesh.ffhl.chaotikum.org:9100"
        - "gw05.ffhl.chaotikum.org:9100"
        - "builder.luebeck.freifunk.net:9100"
        - "srv02.luebeck.freifunk.net:9100"
        - "srv03.luebeck.freifunk.net:9100"
        - "blueberry.luebeck.freifunk.net:9100"
        - "strawberry.luebeck.freifunk.net:9100"
  - job_name: powerdns
    static_configs:
      - targets:
        - "kaisertor.luebeck.freifunk.net:8082"
        - "huextertor.luebeck.freifunk.net:8082"
        - "holstentor.luebeck.freifunk.net:8082"
        - "muehlentor.luebeck.freifunk.net:8082"
        - "gw05.ffhl.chaotikum.org:8082"
  - job_name: fastd
    static_configs:
      - targets:
        - "kaisertor.luebeck.freifunk.net:9281"
        - "muehlentor.luebeck.freifunk.net:9281"
        - "holstentor.luebeck.freifunk.net:9281"
        - "huextertor.luebeck.freifunk.net:9281"
        - "testgw.luebeck.freifunk.net:9281"
  - job_name: bird
    static_configs:
      - targets:
        - "kaisertor.luebeck.freifunk.net:9324"
        - "huextertor.luebeck.freifunk.net:9324"
        - "holstentor.luebeck.freifunk.net:9324"
        - "muehlentor.luebeck.freifunk.net:9324"
        - "gw05.ffhl.chaotikum.org:9324"

  - job_name: "blackbox_ping"
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets:
        - "google.com"
        - "ipv6.google.com"
        - "1.1.1.1"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: target
      - target_label: __address__
        replacement: "blackbox.luebeck.freifunk.net:9115"
