---
- name: create config and scripts directory
  file:
    path: /var/lib/icvpn
    state: directory

- name: clone scripts
  git:
    repo: https://github.com/freifunk/icvpn-scripts.git
    dest: /var/lib/icvpn/icvpn-scripts

- name: clone meta repo
  git:
    repo: https://github.com/freifunk/icvpn-meta.git
    dest: /var/lib/icvpn/icvpn-meta

- name: copy post-merge hook
  copy:
    src: post-merge/icvpn-meta
    dest: /var/lib/icvpn/icvpn-meta/.git/hooks/post-merge
    mode: a+x


- name: run post-merge hook
  command:
    cmd: .git/hooks/post-merge
    chdir: /var/lib/icvpn/icvpn-meta
