---

- name: clone scripts
  git:
    repo: https://github.com/freifunk/icvpn-scripts.git
    dest: /var/lib/icvpn/icvpn-scripts
    version: master


- name: clone meta repo
  git:
    repo: https://github.com/freifunk/icvpn-meta.git
    dest: /var/lib/icvpn/icvpn-meta
    version: master
