---


- name: meta repo
  tags: [icvpn]
  include: icvpn-meta.yml

- name: .network template
  tags: [icvpn]
  template:
    src: 40-icvpn.network.j2
    dest: /etc/systemd/network/40-icvpn.network



# The icvpn tinc configs config
- name: create tinc directory
  tags: [icvpn]
  file:
    state: directory
    dest: /etc/tinc


- name: clone the icvpn config repo
  tags: [icvpn]
  git:
    repo: https://github.com/freifunk/icvpn.git
    dest: /etc/tinc/icvpn
    version: master

- name: apply config template
  tags: [icvpn]
  template:
    src: tinc.conf.j2
    dest: /etc/tinc/icvpn/tinc.conf

- name: copy private key
  copy:
    decrypt: yes
    src: tinc-keys/{{ inventory_hostname }}.priv
    dest: /etc/tinc/icvpn/rsa_key.priv

- name: create git hooks
  tags: [icvpn]
  copy:
    remote_src: yes
    src: /etc/tinc/icvpn/scripts/post-merge
    dest: /etc/tinc/icvpn/.git/hooks/post-merge
    mode: a+xr

- name: first run git hook
  tags: [icvpn]
  command: .git/hooks/post-merge
  args:
    chdir: /etc/tinc/icvpn/

# - systemd:
#     daemon_reload: yes # not required. run daemon-reload before doing any other operations, to make sure systemd has read any changes.
#     state: restarted # not required. choices: reloaded;restarted;started;stopped. C(started)/C(stopped) are idempotent actions that will not run commands unless necessary. C(restarted) will always bounce the service. C(reloaded) will always reload.
#     name: "{{ item }}" # not required. Name of the service. When using in a chroot environment you always need to specify the full name i.e. (crond.service).

- tags: [icvpn]
  include: units.yml
