---

#
# install prometheus
#
- name: install prometheus
  apt:
    update_cache: yes
    state: latest
    name: prometheus

- name: copy prometheus config files
  copy:
    src: prometheus
    dest: /etc/

- name: copy defaults config
  copy:
    src: prometheus-default
    dest: /etc/default/prometheus

- name: restart prometheus
  systemd:
    enabled: yes
    state: restarted
    name: prometheus


#
# Install Grafana
#

- name: add grafana repo pubkey
  shell:
    cmd: wget -q -O - https://packages.grafana.com/gpg.key | apt-key add -
    warn: false

- name: setup grafana repo
  copy:
    src: grafana.list
    dest: /etc/apt/sources.list.d/

- name: install grafana
  apt:
    update_cache: yes
    state: latest
    name: grafana

- name: copy defaults config
  copy:
    src: grafana.ini
    dest: /etc/grafana/
