#!/bin/sh

set -e

DATA=$(git rev-parse --show-toplevel)

../icvpn-scripts/mkbgp -s $DATA -x luebeck -p icvpn_ -d bgp_icvpn -6 > /etc/bird/bird.conf.d/50-bgp_icvpn.conf
../icvpn-scripts/mkroa -s $DATA -x luebeck -m 64 | sed 's/^roa/route/' > /etc/bird/icvpn_roa.conf


systemctl try-reload-or-restart bird.service

exit 0
