#!/bin/bash

fail() {
  echo "$1" >&2
  exit 1
}

BASE=$(git rev-parse --show-toplevel)
TINCCFG=$BASE/tinc.conf
test -w $TINCCFG || fail "ERR: $TINCCFG is not writeable"

sed -i '/^ConnectTo/d' $TINCCFG

while read HOST; do
  # skip hosts without address
  grep -iq '^Address' -- hosts/"$HOST" || continue

  echo "ConnectTo = $HOST" >> $TINCCFG
done < metanodes

systemctl try-reload-or-restart tinc@icvpn.service

exit 0
