- name: install bird and bird exporter
  apt:
    update_cache: true
    state: latest
    name:
      - bird2
      - prometheus-bird-exporter


- name: create bird.conf.d
  file:
    state: directory
    path: /etc/bird/bird.conf.d


# BIRD

- name: copy static bird configs
  notify: restart bird
  copy:
    src: "{{ item }}"
    dest: /etc/bird/
  with_fileglob: "bird/*"


- name: copy host specific configs
  notify: restart bird
  copy:
    src: "{{ item }}"
    dest: /etc/bird/bird.conf.d/
  with_fileglob: "host/{{ inventory_hostname }}/bird.conf.d/*"

- name: generate and copy host specific bird configs
  notify: restart bird
  template:
    src: bird/bird_host_vars.conf.j2
    dest: /etc/bird/bird_host_vars.conf


- name: remove old ibgp config
  notify: restart bird
  file:
    state: absent
    path: /etc/bird/bird.conf.d/10-ibgp.conf

- name: remove old ospf config
  notify: restart bird
  file:
    state: absent
    path: /etc/bird/bird.conf.d/{{ item }}
  loop:
    - 40-internal-ospf.conf
    - 60-ospf-internal.conf

- name: generate ospf configs
  notify: restart bird
  template:
    src: "bird/{{ item }}.j2"
    dest: "/etc/bird/bird.conf.d/40-{{ item }}"
  loop:
  - ospf_ffhl4.conf
  - ospf_ffhl6.conf
