---

- name: download prometheus-fastd-exporter
  get_url:
    url: https://freifunk-luebeck.pages.chaotikum.org/prometheus-fastd-exporter/prometheus-fastd-exporter.deb
    dest: /tmp/prometheus-fastd-exporter.deb

- name: install prometheus-fastd-exporter
  apt:
    state: present
    deb: /tmp/prometheus-fastd-exporter.deb

- name: enable prometheus-fastd-exporter
  systemd:
    enabled: yes
    name: prometheus-fastd-exporter
