---
- include: yaourt.yml
- include: update.yml
- include: software.yml
- lineinfile: dest=/etc/ssh/sshd_config regexp="^#?PermitRootLogin" line="PermitRootLogin without-password"
- user: name=fastd system=yes home=/etc/fastd
- user: name=root shell=/bin/zsh
- command: grub-mkconfig -o /boot/grub/grub.cfg
- copy: src=etc/ dest=/etc
- copy: src=netconfig/{{ inventory_hostname }}/ dest=/etc/systemd/network
  ignore_errors: True
- copy: src=host/{{ inventory_hostname }}/etc/ dest=/etc
  ignore_errors: True
- file: state=link src=/usr/share/zoneinfo/Europe/Berlin dest=/etc/localtime
- template: src=fastd-mac.j2 dest=/etc/fastd/ffhl-mesh-vpn/mac
- template: src=fastd-mac-2.j2 dest=/etc/fastd/ffhl-mesh-vpn-2/mac
- template: src=fastd-gw-mac.j2 dest=/etc/fastd/ffhl-gw-vpn/mac
- template: src=dhcpd.conf.j2 dest=/etc/dhcpd.conf
- template: src=radvd.conf.j2 dest=/etc/radvd.conf
- template: src=10-freifunk-hl.netdev.j2 dest=/etc/systemd/network/10-freifunk-hl.netdev
- template: src=12-freifunk-hl.network.j2 dest=/etc/systemd/network/12-freifunk-hl.network
- command: systemctl daemon-reload
- file: path=/var/net-snmp state=directory
- copy: content="createUser guest SHA guestffhl AES guestffhl" dest=/var/net-snmp/snmpd.conf
- lineinfile: dest=/etc/iproute2/rt_tables line="42\tfreifunk"
- include: bird.yml
  tags:
    - bird
- include: ffhl-dns.yml
- include: ffhl-peers.yml
  ignore_errors: True
- include: units.yml
