---

- name: install packages
  tags: [dns, powerdns]
  apt:
    state: present
    name:
      - dnsdist
      - pdns-recursor
      - pdns-server
      - pdns-backend-bind


- import_tasks: dnsdist.yml
  tags: [dnsdist]

- import_tasks: powerdns.yml
  tags: [powerdns]
