---


- name: copy systemd services and timers
  copy:
    src: systemd/
    dest: /etc/systemd/system/

- name: copy dnsdist configs
  copy:
    src: dnsdist
    dest: /etc/

- name: remove default bind-backend config
  file:
    path: /etc/powerdns/pdns.d/bind.conf
    state: absent

- name: remove old dns repo
  file:
    path: /var/local/ffhl-dns
    state: absent


- name: restart powerdns
  systemd:
    daemon_reload: yes
    enabled: yes
    state: restarted
    name: "{{ item }}"
  with_items:
    - pdns-recursor.service
    - pdns.service
    - dnsdist.service
    - update-ffhl-dns.timer
    - update-ffhl-dns.service
