---

- name: remove default bind-backend config
  file:
    path: /etc/powerdns/pdns.d/bind.conf
    state: absent
  notify: restart pdns

- name: copy powerdns configs
  notify:
    - restart pdns
    - restart pdns-recursor
  copy:
    src: powerdns
    dest: /etc/

# add update script
- name: copy update script
  notify: restart update-ffhl-dns
  template:
    src: update-dns.sh
    dest: /usr/local/lib/ffhl/
    mode: 0775

- name: copy systemd services and timers
  notify: reload systemd
  copy:
    src: systemd/
    dest: /etc/systemd/system/

- name: enable update-ffhl-dns.timer
  systemd:
    enabled: true
    name: update-ffhl-dns.timer
