ip4: 10.130.0.252
ip6: 2001:67c:2d50::bbaa
ip6_ula: fdef:ffc0:3dd7::bbaa
freifunk_mac: de:ad:ca:fe:bb:aa
fastd_mesh_mac: de:ad:ca:fe:bb:bb
fastd_gw_mac: de:ad:ca:fe:bb:cc
dhcpd_start: 10.130.24.1
dhcpd_end: 10.130.31.254
# edit this before deploying on final servers!!!
exit_iface: eth0

units_enable:
  - batman.service
