ip4: 10.130.0.255
ip6: 2001:67c:2d50::aa
ip6_ula: fdef:ffc0:3dd7::aa
fastd_mesh_mac: de:ad:ca:fe:aa:bb
fastd_gw_mac: de:ad:ca:fe:aa:cc
freifunk_mac: de:ad:ca:fe:aa:aa
dhcpd_start: 10.130.16.1
dhcpd_end: 10.130.23.254
internet_iface_mac: 52:54:00:57:84:a3
