# MAC address: de:ad:ca:fe:<gateway>:<iface-type>

ip4: 10.130.0.255
ip6: 2001:67c:2d50::aaaa
ip6_ula: fdef:ffc0:3dd7::aaaa
freifunk_mac: de:ad:ca:fe:aa:aa
fastd_mesh_mac: de:ad:ca:fe:aa:bb
fastd_gw_mac: de:ad:ca:fe:aa:cc
dhcpd_start: 10.130.16.1
dhcpd_end: 10.130.23.254

# the out-interface for NAT
exit_iface: enp1s0

# ICVPN variables
icvpn_name: luebeck2
icvpn_ip4: 10.207.0.131
icvpn_ip6: fec0::a:cf:0:83
