---

- name: copy base configs
  tags: [base, etc, apt]
  copy:
    src: etc/
    dest: /etc

- name: copy host specific configs
  tags: [bird]
  copy:
    src: host/{{ inventory_hostname }}/etc/
    dest: /etc



- name: Disable root login with password
  tags: [base]
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?PermitRootLogin"
    line: "PermitRootLogin without-password"


# configurations and stuff
- name: set local timezone
  file:
    state: link
    src: /usr/share/zoneinfo/Europe/Berlin
    dest: /etc/localtime

- name: set locales
  tags: [base]
  block:
    - name: enable en_US locals
      lineinfile: dest=/etc/locale.gen line="en_US.UTF-8 UTF-8"
    - name: enable de_DE locals
      lineinfile: dest=/etc/locale.gen line="de_DE.UTF-8 UTF-8"
    - name: generate locales
      command: locale-gen


- name: copy scripts
  tags: [base]
  copy:
    src: scripts/
    dest: /usr/local/lib/ffhl/
    mode: a+x

- name: add trusted ssh hosts to knonw_hosts
  loop: "{{ ssh_known_hosts }}"
  shell:
    cmd: ssh-keyscan -4 -H {{ item }} >> /root/.ssh/known_hosts
    # creates: /root/.ssh/known_hosts


- name: reload sysctl
  command: sysctl -p --system
