---
- template: src=bird/bird_host.conf.j2 dest=/etc/bird/bird_host.conf
  tags: ["bird"]

  
# - template: src=bird/bird6_host.conf.j2 dest=/etc/bird/bird6_host.conf
#   tags: ["bird"]
# - name: restart bird
#   tags: ["bird"]
#   systemd:
#     state: restarted
#     name: bird.service
