---

- name: copy static bird configs
  copy: src=bird dest=/etc/
  tags: [bird]

- name: generate dynamic bird configs
  template: src=bird/bird_host.conf.j2 dest=/etc/bird/bird_host.conf
  tags: ["bird"]

- name: generate ibgp configs
  template: src=bird/bird_ibgp.conf.j2 dest=/etc/bird/bird_ibgp.conf
  tags: ["bird"]

- name: restart bird
  tags: ["bird"]
  systemd:
    state: restarted
    name: bird.service
