---
- name: copy base configs
  tags: [base, etc, apt]
  copy:
    src: etc/
    dest: /etc

- name: copy scripts
  tags: [base]
  copy:
    src: scripts/
    dest: /usr/local/lib/ffhl/
    mode: a+x

- name: install packages
  include: software.yml
  tags: [base, apt, software]

# configurations and stuff
- name: set local timezone
  file: state=link src=/usr/share/zoneinfo/Europe/Berlin dest=/etc/localtime

- name: set locales
  tags: [base]
  block:
    - lineinfile: dest=/etc/locale.gen line="en_US.UTF-8 UTF-8"
    - lineinfile: dest=/etc/locale.gen line="de_DE.UTF-8 UTF-8"
    - command: locale-gen

- name: base config
  tags: [base]
  include_tasks:
    file: base.yml
    apply:
      tags: [base]

- name: Disable root login with password
  tags: [base]
  lineinfile: dest=/etc/ssh/sshd_config regexp="^#?PermitRootLogin" line="PermitRootLogin without-password"

- name: reload sysctl
  command: sysctl -p --system

- name: add freifunk routing table
  tags: [network]
  lineinfile:
    dest: /etc/iproute2/rt_tables
    line: "42\tfreifunk"

- name: copy host specific configs
  copy: src=host/{{ inventory_hostname }}/etc/ dest=/etc
  tags: [bird]

- name: networkd templates
  tags: [systemd-networkd]
  block:
    - name: apply network templates
      template: src=network/10-ffhl.netdev.j2 dest=/etc/systemd/network/10-ffhl.netdev
    - name: apply netowrk templates
      template: src=network/12-ffhl.network.j2 dest=/etc/systemd/network/12-ffhl.network
    - name: copy network configs
      copy: src=systemd-networkd/ dest=/etc/systemd/network/
    - name: restart systemd-networkd
      systemd:
        state: restarted
        name: systemd-networkd

- name: template iptables
  tags: [iptables, network]
  block:
    - name: iptables4 template
      template: src=iptables/rules.v4 dest=/etc/iptables/rules.v4
    - name: iptables6 template
      template: src=iptables/rules.v6 dest=/etc/iptables/rules.v6
    - name: reload iptables
      systemd:
        state: restarted
        name: netfilter-persistent.service

# sometimes disabled (dunno why)
- name: enable systemd-networkd
  tags: [network]
  systemd:
    enabled: yes
    name: systemd-networkd

- name: mesh-vpn
  tags: [fastd, mesh-vpn]
  include: mesh-vpn.yml

- name: gwvpn
  tags: [gwvpn, fastd]
  include: gwvpn.yml

- name: reload systemd
  systemd:
    daemon_reload: yes


- include: radvd.yml
  tags: [network, radvd]
- include: dhcpd.yml
  tags: [network, dhcp]

- include: bird.yml
  tags: [bird]

- include: units.yml
  tags: [base]
