---

- name: base config
  tags: [base]
  import_tasks: base.yml

- name: install packages
  tags: [software, base, apt]
  import_tasks: software.yml

- name: configure network
  tags: [network]
  import_tasks: network.yml

- name: gwvpn
  tags: [gwvpn, fastd]
  import_tasks: gwvpn.yml

- import_tasks: units.yml
  tags: [base, units]
