---
- include: software.yml

- name: Disable root login with password
  lineinfile: dest=/etc/ssh/sshd_config regexp="^#?PermitRootLogin" line="PermitRootLogin without-password"

- name: copy base configs
  copy: src=etc/ dest=/etc
  tags: [fastd]

- name: copy host specific configs
  copy: src=host/{{ inventory_hostname }}/etc/ dest=/etc
  tags: [bird, fastd]


# configurations and stuff

- name: set local timezone
  file: state=link src=/usr/share/zoneinfo/Europe/Berlin dest=/etc/localtime

- name: configure ntp
  blockinfile:
    path: /etc/ntp.conf
    block: |
      restrict fdef:ffc0:3dd7:: mask ffff:ffff:ffff:ffff:: nomodify notrap nopeer
      restrict 2001:67c:2d50:: mask ffff:ffff:ffff:ffff:: nomodify notrap nopeer

- name: networkd templates
  tags: [systemd-networkd]
  block:
    - template: src=network/10-ffhl.netdev.j2 dest=/etc/systemd/network/10-ffhl.netdev
    - template: src=network/12-ffhl.network.j2 dest=/etc/systemd/network/12-ffhl.network
    - name: copy network configs
      copy: src=systemd-networkd/ dest=/etc/systemd/network/
    - name: restart systemd-networkd
      systemd:
        state: restarted
        name: systemd-networkd


- name: template iptables
  tags: [iptables, networking]
  block:
    - template: src=iptables/rules.v4 dest=/etc/iptables/rules.v4
    - template: src=iptables/rules.v6 dest=/etc/iptables/rules.v6
    - name: reload iptables
      systemd:
        state: restarted
        name: iptables.service


# sometimes disabled (dunno why)
- name: enable systemd-networkd
  tags: [networking]
  systemd:
    enabled: yes
    name: systemd-networkd


- name: mesh-vpn
  tags: [debug, fastd, mesh-vpn]
  include: mesh-vpn.yml

- name: gwvpn
  tags: ['gwvpn', 'fastd']
  include: gwvpn.yml


- name: reload systemd
  systemd:
    daemon_reload: yes

- include: radvd.yml
- include: dhcpd.yml
- include: powerdns.yml
  tags: [powerdns]

- name: add freifunk routing table
  tags: [networking]
  lineinfile:
    dest: /etc/iproute2/rt_tables
    line: "42\tfreifunk"

- include: bird.yml
  tags:
    - bird

- include: units.yml
