---

- name: base config
  tags: [base]
  import_tasks: base.yml

- name: install packages
  include: software.yml
  tags: [software, base, apt]


- name: configure network
  include: network.yml
  tags: [network]

- name: gwvpn
  tags: [gwvpn, fastd]
  include: gwvpn.yml

- name: reload systemd
  systemd:
    daemon_reload: yes

- include: units.yml
  tags: [base, units]
