---

- name: add freifunk routing table
  tags: [network]
  lineinfile:
    dest: /etc/iproute2/rt_tables
    line: "42\tfreifunk"


- name: copy network config templates
  tags: [networkd, network]
  notify: restart systemd-networkd
  template:
    src: "network/{{ item }}.j2"
    dest: "/etc/systemd/network/{{ item }}"
  loop:
    - 10-ffhl.netdev
    - 12-ffhl.network


- name: template iptables
  tags: [iptables, network]
  notify: reload iptables
  block:
    - name: iptables4 template
      template: src=iptables/rules.v4 dest=/etc/iptables/rules.v4
    - name: iptables6 template
      template: src=iptables/rules.v6 dest=/etc/iptables/rules.v6


# sometimes disabled (dunno why)
- name: enable systemd-networkd
  tags: [network]
  systemd:
    enabled: yes
    name: systemd-networkd
