---

- name: mask display-manager
  systemd:
    masked: yes
    name: display-manager.service

- name: reload systemd
  systemd:
    daemon_reload: yes

# - name: stop bird
#   systemd:
#     state: stopped
#     name: bird.service

# - name: restart services
#   systemd:
#     enabled: no
#     name: "{{ item }}"
#   with_items:
#     - batman.service


- name: restart services
  systemd:
    state: restarted
    enabled: yes
    name: "{{ item }}"
  with_items:
    - bird.service
    - haveged.service
    - netfilter-persistent.service
    - isc-dhcp-server.service
    - pdns-recursor.service
    - radvd.service
    - systemd-networkd.service
    - update-ffhl-dns.timer
    - update-ffhl-mesh-vpn.timer
    - systemd-journald
    - fastd
    - prometheus-fastd-exporter
