---

# - name: stop bird
#   systemd:
#     state: stopped
#     name: bird.service

# - name: restart services
#   systemd:
#     enabled: no
#     name: "{{ item }}"
#   with_items:
#     - batman.service


- name: restart services
  systemd:
    daemon_reload: yes
    state: restarted
    enabled: yes
    name: "{{ item }}"
  with_items:
    - bird.service
    - haveged.service
    - netfilter-persistent.service
    - systemd-networkd.service
    - systemd-journald
    - fastd
    - prometheus-fastd-exporter

- name: stop, mask and disable selected services
  tags: [systemd]
  systemd:
    masked: yes
    state: stopped
    enabled: no
    name: "{{ item }}"
  loop: "{{ masked_services | default('[]') }}"
