---
- command: systemctl mask display-manager.service

- command: systemctl daemon-reload

# - name: stop bird
#   systemd:
#     state: stopped
#     name: bird.service

- name: restart services
  systemd:
    state: restarted
    enabled: yes
    name: "{{ item }}"
  with_items:
    - batman.service
    - bird.service
    - haveged.service
    - netfilter-persistent.service
    - isc-dhcp-server.service
    - pdns-recursor.service
    - radvd.service
    - systemd-networkd.service
    - update-ffhl-dns.timer
    - update-ffhl-mesh-vpn.timer
    - systemd-journald
    - fastd
