---
- command: systemctl mask display-manager.service

- command: systemctl daemon-reload

- name: stop bird
  systemd:
    state: stopped
    name: bird.service

- name: restart services
  systemd:
    state: restarted
    enabled: yes
    name: "{{ item }}"
  with_items:
    - "fastd@ffhl_mesh_gwvpn.service"
    - "fastd@ffhl_mesh_vpn.service"
    - batman.service
    - bird.service
    - haveged.service
    - ip6tables.service
    - iptables.service
    - isc-dhcp-server.service
    - ntp.service
    - pdns-recursor.service
    - radvd.service
    - sshd.service
    - systemd-networkd.service
    - update-ffhl-dns.timer
    - update-ffhl-mesh-vpn.timer
