---

- name: copy base configs
  tags: [base, etc, apt]
  copy:
    src: etc/
    dest: /etc

- name: install tools
  apt:
    autoremove: yes
    update_cache: yes
    state: present
    name:
      # necessary packets
      - bird2
      - prometheus-bird-exporter


- name: copy host specific configs
  tags: [bird, etc]
  copy:
    src: host/{{ inventory_hostname }}/etc/
    dest: /etc
