---

- name: install packages
  apt:
    autoremove: yes
    update_cache: yes
    state: present
    name:
      - batctl
      - fastd
      - iproute2
      - isc-dhcp-server
      - radvd

- name: load batman-adv
  modprobe:
    name: batman-adv
    state: present
