---

- name: process dhcpd templates
  notify: restart dhcpd
  template:
    src: dhcpd/dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf

- name: tell dhcpd what interfaces it should listen
  lineinfile:
    path: /etc/default/isc-dhcp-server
    regexp: '^INTERFACESv4='
    line: INTERFACESv4="ffhl"

- name: enable dhcpd
  when: exit_traffic
  systemd:
    enabled: yes
    masked: no
    name: isc-dhcp-server.service

- name: disable dhcpd
  when: exit_traffic is not defined or not exit_traffic
  notify: stop dhcpd
  systemd:
    enabled: no
    masked: yes
    name: isc-dhcp-server.service
