---

- name: process dhcpd templates
  template:
    src: dhcpd/dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf

- name: tell dhcpd what interfaces it should listen
  lineinfile:
    path: /etc/default/isc-dhcp-server
    regexp: '^INTERFACESv4='
    line: INTERFACESv4="ffhl"

- name: restart dhcpd
  when: exit_traffic == false
  systemd:
    enabled: no
    state: stopped
    name: isc-dhcp-server.service

- name: restart dhcpd
  when: exit_traffic
  systemd:
    enabled: yes
    state: restarted
    name: isc-dhcp-server.service
