---
- name: create fastd user
  user:
    name: fastd
    system: yes
    home: /etc/fastd

- name: create fastd config dirs
  loop: "{{ mesh_vpn_instances }}"
  file:
    path: /etc/fastd/{{ item.name }}
    state: directory

- name: copy fastd config templates
  loop: "{{ mesh_vpn_instances }}"
  template:
    src: mesh-vpn/fastd.conf
    dest: /etc/fastd/{{ item.name }}/fastd.conf
    mode: '0640'


- name: create fastd-up script
  loop: "{{ mesh_vpn_instances }}"
  template:
    src: mesh-vpn/fastd-up
    dest: /etc/fastd/{{ item.name }}/fastd-up
    mode: 0755


# configure peers git
# add update script
- name: copy update script
  template:
    src: mesh-vpn/update-meshvpn-keys.sh
    dest: /usr/local/lib/ffhl/
    mode: 0775

- name: install mesh-vpn peer update service
  copy:
    src: systemd/
    dest: /etc/systemd/system/
    owner: root


# - name: run meshvpn-keys update script
#   command: /usr/local/lib/ffhl/update-meshvpn-keys.sh


- name: enable meshvpn peer update job
  systemd:
    daemon_reload: yes
    enabled: yes
    state: restarted
    name: update-ffhl-mesh-vpn.timer


# enable fastd instances
- name: enable fastd instances
  loop: "{{ mesh_vpn_instances }}"
  systemd:
    enabled: yes
    daemon-reload: yes
    state: restarted
    name: fastd@{{ item.name }}


# download public keys to our local machine
- name: create public key files
  loop: "{{ mesh_vpn_instances }}"
  shell:
    cmd: fastd --show-key -c /etc/fastd/{{ item.name }}/fastd.conf > /etc/fastd/{{ item.name }}/pubkey.key

- name: fetch public keys
  loop: "{{ mesh_vpn_instances }}"
  fetch:
    src: /etc/fastd/{{ item.name }}/pubkey.key
    dest: artifacts/
