---
- name: radvd templates
  template:
    src: radvd/radvd.conf.j2
    dest: /etc/radvd.conf

- name: restart radvd
  when: exit_traffic
  systemd:
    state: restarted
    enabled: yes
    name: radvd


- name: restart radvd
  when: not exit_traffic
  systemd:
    state: stopped
    enabled: no
    name: radvd
