---
- name: radvd templates
  notify: restart radvd
  template:
    src: radvd/radvd.conf.j2
    dest: /etc/radvd.conf

- name: enable radvd
  notify: stop radvd
  systemd:
    masked: no
    enabled: yes
    name: radvd.service


- name: disable radvd
  when: not exit_traffic
  notify: restart radvd
  systemd:
    masked: yes
    enabled: no
    name: radvd
