- name: install wireguard tools
  apt:
    state: latest
    name: wireguard-tools

- name: copy private key files
  notify: restart systemd-networkd
  copy:
    mode: "0640"
    owner: root
    group: systemd-network
    src: "underlay_vpn/{{ inventory_hostname }}.key"
    dest: /etc/systemd/wg0-priv.key

- name: generate wireguard config
  notify: restart systemd-networkd
  template:
    src: 10-wg0.netdev.j2
    dest: /etc/systemd/network/10-wg0.netdev

- name: generate network config
  notify: restart systemd-networkd
  template:
    src: 10-wg0.network.j2
    dest: /etc/systemd/network/10-wg0.network
