---

- name: Disable root login with password
  tags: [base]
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?PermitRootLogin"
    line: "PermitRootLogin prohibit-password"


# configurations and stuff
- name: set local timezone
  file:
    state: link
    src: /usr/share/zoneinfo/Europe/Berlin
    dest: /etc/localtime


- name: set locales
  tags: [base]
  block:
    - name: enable en_US locale
      lineinfile: dest=/etc/locale.gen line="en_US.UTF-8 UTF-8"
    - name: enable de_DE locale
      lineinfile: dest=/etc/locale.gen line="de_DE.UTF-8 UTF-8"
    - name: generate locales
      command: locale-gen

- name: Copy authorized keys file
  ansible.builtin.copy:
    src: authorized_keys
    dest: /root/.ssh/authorized_keys
    owner: root
    group: root

- name: copy base configs
  tags: [base, etc, apt, powerdns]
  copy:
    src: etc/
    dest: /etc


- name: install base tools
  include: software.yml
  tags: [base, apt, software]
