---
- name: base config
  tags: [base]
  import_tasks:
    file: base.yml

- name: install packages
  include: software.yml
  tags: [base, apt, software]

- name: setup monitoring
  include: monitoring.yml
  tags: [base, apt, software]

- name: setup nginx
  include: nginx.yml
  tags: [nginx]

- name: ffdyndns
  tags: [ffdyndns]
  import_tasks:
    file: ffdyndns.yml
