---
- name: base config
  tags: [base]
  import_tasks: base.yml

- name: install packages
  import_tasks: software.yml
  tags: [base, apt, software]

- name: setup nginx
  tags: [nginx]
  import_tasks: nginx.yml

- name: setup caddy
  tags: [caddy]
  import_tasks: caddy.yml

- name: ffdyndns
  tags: [ffdyndns]
  import_tasks: ffdyndns.yml
