---
- name: base config
  tags: [base]
  import_tasks:
    file: base.yml

- name: install packages
  import_tasks: software.yml
  tags: [base, apt, software]

- name: setup monitoring
  tags: [monitoring]
  import_tasks: monitoring.yml

- name: setup nginx
  tags: [nginx]
  import_tasks: nginx.yml

- name: ffdyndns
  tags: [ffdyndns]
  import_tasks:
    file: ffdyndns.yml
