---
- name: copy prometheus config files
  copy:
    src: prometheus
    dest: /etc/

- name: restart prometheus
  systemd:
    state: restarted
    name: prometheus


#
# Install Grafana
#

- name: add grafana repo pubkey
  shell:
    cmd: wget -q -O - https://packages.grafana.com/gpg.key | apt-key add -
    warn: false

- name: setup grafana repo
  copy:
    src: grafana.list
    dest: /etc/apt/sources.list.d/

- name: install grafana
  apt:
    update_cache: yes
    state: present
    name: grafana
