---

- name: install nginx
  apt:
    state: present
    install_recommends: no
    name:
      - openssl
      - nginx-full
      - libnginx-mod-http-fancyindex
      - libnginx-mod-http-headers-more-filter

- name: generate dhparams (can take a while)
  command:
    cmd: openssl dhparam -out /etc/nginx/dhparam.pem 4096
    creates: /etc/nginx/dhparam.pem

- name: copy snippets
  notify:
    - restart nginx
    - check nginx config
  copy:
    src: nginx/snippets
    dest: /etc/nginx/

- name: copy available sites
  notify:
    - restart nginx
    - check nginx config
  copy:
    src: "{{ item }}"
    dest: /etc/nginx/sites-available/
  with_fileglob: 'nginx/sites/*'


- name: enable sites
  block:
    - name: remove all enabled sites
      changed_when: false
      file:
        state: absent
        path: "/etc/nginx/sites-enabled/"
    - name: create enabled-sites directory
      notify:
        - restart nginx
        - check nginx config
      file:
        state: directory
        path: "/etc/nginx/sites-enabled"
    - name: enable selected sites
      changed_when: false
      notify: restart nginx
      file:
        state: link
        src: "../sites-available/{{ item | basename }}"
        dest: "/etc/nginx/sites-enabled/{{ item | basename }}"
      with_fileglob: 'nginx/sites/*'
