---

- name: install python3-apt
  command:
    cmd: apt-get install -y python3-apt

- name: remove packages that are not needed
  apt:
    update_cache: yes
    state: absent
    name:
      - cron-apt
      - mutt

- name: install tools
  apt:
    autoremove: yes
    update_cache: yes
    state: present
    name:
      # essential packages
      - git
      - openssh-server
      - prometheus-node-exporter
      - python3-apt
      - apt-transport-https
      - curl
      # other useful tools
      - apt-file
      - bridge-utils
      - dnsutils
      - htop
      - iftop
      - iperf3
      - iputils-ping
      - jq
      - molly-guard
      - openssh-client
      - python3-yaml
      - socat
      - tcpdump
      - vim
      - wget
      - rsync
      - nmap
