---

- name: copy static bird configs
  copy: src=bird dest=/etc/

- name: generate and copy host specific bird config
  template: src=bird/bird_host.conf.j2 dest=/etc/bird/bird_host.conf

- name: generate ibgp configs
  template: src=bird/bird_ibgp.conf.j2 dest=/etc/bird/bird.conf.d/10-ibgp.conf

- name: restart bird
  systemd:
    state: restarted
    name: bird.service
