name = "FFdynDNS"
description = "DynDNS Service"
server_web_url = "ffdyn.net"
database = "./db.rocks"
dns_server = "10.130.0.104"
bind_address = "0.0.0.0"
bind_port = 8053


[[domain]]
name = "ffdyn.net."
description = "Freifunk  Premium Domain"
allowed_ips = ["0.0.0.0/0", "::/0"]
validity = 1
